name: CI

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: action/checkout@v2

      - name: Run a on-line script
        run: echo Hello, world!

      - name: Run a multi-line scrip
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
    
